### PR TITLE
Task22

### PR DESCRIPTION
**Pull request by yana-may25**

### CODE REVIEW

**Comment by MrOlegKravchenko** [comment]
Please separate code into html and js files.
Import mountains from ext folder.
After changes share the evidence (screenshot).

**Comment by yana-may25** [comment]
image

**Comment by yana-may25** [comment]
so look,
I tried making them different files and launch that in browser as a page
aaaand there's CORS error :(
what should I do?

**Comment by MrOlegKravchenko** [comment]
I was blind a little)
1. Get back your css file
2. 
```
<head>
  <link rel="stylesheet" href="./task22.css">
  <title>Page Title</title>
    <!--  we need this variable to be predefined for use  -->
  <script type="text/javascript" src="../../ext/mountains.js"></script>
  <script type="text/javascript" src="./task22.js"></script>
</head>

<body>
<h1>Mountains</h1>
<div id="mountains"></div>
<script>
  document.body.appendChild(addTable(MOUNTAINS));
</script>
</body>
```

**Pull request merged**
