### PR TITLE
Task26

### PR DESCRIPTION
**Pull request by yana-may25**
Hi
I understand my first commit is not how the task was intended, as I see the hint suggests it should be done with a loop. I will therefore try to do it another way, but this solution also works, so I will just leave it here for now :)

### CODE REVIEW

**Comment by MrOlegKravchenko** [comment]
Good enough!

**Comment by MrOlegKravchenko** [comment]
But)
Please separate code into html and js files.
After changes share the evidence (gif or mp4).

**Comment by yana-may25** [comment]
look, this is the latest solution with the array. I don't like the trail remaining on the screen when the pointer is static and when the pointer is out of scope



https://user-images.githubusercontent.com/75950794/225936454-3ee3e817-d908-40d2-afae-8c7b18539d8f.mp4

and here's my initial solution (task26 init). It looks much better, but I don't think it's an elegant solution to have the pagecontext reset every time

https://user-images.githubusercontent.com/75950794/225937074-be190ccd-c6c1-49d9-8272-a2c4dcaf7f08.mp4

**Comment by MrOlegKravchenko** [comment]
I admire you commiteness to the work.
And that you decided it is not perfect enough!
The original point of this task was to look how you handle this mouse event and you did it 120% right!

**Pull request merged**
